# Generated by Django 5.2.6 on 2025-09-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
